services:
  etl-rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
      RABBITMQ_MANAGEMENT: true
    volumes:
      - etl-mq-data:/var/lib/rabbitmq

volumes:
  etl-mq-data:
